services:
  fastapi:
    build: ./fastapi
    env_file: ./fastapi/.env
    volumes:
      - ./fastapi:/app
      - ./uploads:/uploads
      - ./logs:/logs
    ports:
      - "8000:5888"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    env_file: ./fastapi/.env
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  vuejs:
    build: ./vuejs
    volumes:
      - ./vuejs:/app # sync code changes
      - /app/node_modules # prevent overwriting node_modules
    ports:
      - "5173:5173"
    depends_on:
      - fastapi

  nginx:
    image: nginx:1.26-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - ./uploads:/uploads
    depends_on:
      - vuejs
  
  # zeppelin:
  #   image: crypto-stream-zeppelin
  #   container_name: zeppelin
  #   depends_on:
  #     - jobmanager
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     ZEPPELIN_ADDR: 0.0.0.0
  #     ZEPPELIN_PORT: 8080

volumes:
  postgres-data:
