version: "3.8"

services:
  kafka:
    image: bitnami/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # --- KRaft mode ---
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_data:/bitnami/kafka

  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.1
    container_name: schema-registry
    ports:
      - "8085:8085"
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=PLAINTEXT://kafka:9092
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8085
    depends_on:
      - kafka

  jobmanager:
    image: bitnami/flink:1.20.0
    container_name: jobmanager
    ports:
      - "8081:8081"   # Flink Web UI
    environment:
      - FLINK_MODE=jobmanager
    command: jobmanager
    depends_on:
      - kafka
      - schema-registry

  taskmanager:
    image: bitnami/flink:1.20.0
    container_name: taskmanager
    environment:
      - FLINK_MODE=taskmanager
      - FLINK_JOB_MANAGER_HOST=jobmanager
    command: taskmanager
    depends_on:
      - jobmanager

volumes:
  kafka_data: