services:
  fastapi:
    build: ./fastapi
    restart: always
    env_file: ./fastapi/.env
    volumes:
      - ./fastapi:/app
      - ./uploads:/uploads
      - ./logs:/logs
    ports:
      - "8000:5888"
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    restart: always
    env_file: ./fastapi/.env
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  vuejs:
    build: ./vuejs
    volumes:
      - ./vuejs:/app # sync code changes
      - /app/node_modules # prevent overwriting node_modules
    ports:
      - "5173:5173"
    depends_on:
      - fastapi

  nginx:
    image: nginx:1.26-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - ./uploads:/uploads
    depends_on:
      - vuejs

volumes:
  postgres:
