services:
  spark-master:
    image: crypto-batch-spark
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./jupyter/data:/data
      - ./spark/extra-jars:/opt/spark-extra-jars/
    ports:
      - "7077:7077" # Spark master port
      - "8080:8080" # Spark UI

  spark-worker:
    image: crypto-batch-spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
    depends_on:
      - spark-master
    volumes:
      - ./jupyter/data:/data
      - ./spark/extra-jars:/opt/spark-extra-jars/
    ports:
      - "8081:8081" # Worker UI

  jupyter:
    image: crypto-batch-jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter/data:/data # shared folder
      - ./spark/extra-jars:/opt/spark-extra-jars/
    working_dir: /data # <-- important!
    environment:
      - JUPYTER_TOKEN=123456
    depends_on:
      - spark-master
      - spark-worker
      - minio

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data

  hive-metastore:
    image: crypto-batch-hive-metastore
    environment:
      - SERVICE_NAME=metastore
      - DB_DRIVER=postgres
      - HIVE_METASTORE_DRIVER=org.postgresql.Driver
      - HIVE_METASTORE_JDBC_URL=jdbc:postgresql://postgres:5432/metastore
      - HIVE_METASTORE_USER=hive
      - HIVE_METASTORE_PASSWORD=hive
      - HIVE_CUSTOM_CONF_DIR=/opt/hive/conf
    ports:
      - "9083:9083"
    depends_on:
      - postgres
    volumes:
      - ./hive/conf:/opt/hive/conf
      - ./spark/extra-jars:/opt/spark-extra-jars/  # For Spark only

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=metastore
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  minio:
  postgres:
